version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Authentication.JwtBearer"
    open-pull-requests-limit: 128

  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.BackgroundJob"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128

  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.Tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128

  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.Stack"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
