version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
    target-branch: sqs
    
  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.Tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
    target-branch: sqs
    
  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.Stack"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
    target-branch: sqs
